### ISSUE TITLE
Config.json file is missing

### ISSUE THREAD

**Issue by AnilB87** [CogComp/perspectroscope#3]
Hi,

I tried to clone the project and run it. However the command " python3 manage.py makemigrations app" leads to the following error as the config file is missing:
 
No such file or directory: 'config/config.json'

Please can you help with the location of the config.json file

**Comment by schen149** [comment]
Thanks for pointing this out! I've added the config file now. You will need to start your own google custom search engine and specify your api key + engine id for it to work.
More details on CSE -- https://developers.google.com/custom-search/docs/tutorial/creatingcse

Resolved via #4.
